# Generated by Django 4.2.7 on 2023-11-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('excel_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('create_day', models.CharField(max_length=255)),
            ],
        ),
    ]
