# Generated by Django 4.2.7 on 2023-11-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_website', '0002_records'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='title',
            new_name='name',
        ),
    ]
