# Generated by Django 4.2.7 on 2023-12-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_website', '0003_rename_title_records_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='your_upload_path/')),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
